# Background and foreground colors
background = #141520
foreground = #c9cbe8

# Standard colors
palette = 0=#141520
palette = 1=#a5a6d0
palette = 2=#b7bae1
palette = 3=#c0c4ec
palette = 4=#a7aad5
palette = 5=#b0afda
palette = 6=#babde5
palette = 7=#c9cbe8

# Bright colors
palette = 8=#626369
palette = 9=#c8c7fc
palette = 10=#c1c2ff
palette = 11=#caccff
palette = 12=#c7c9ff
palette = 13=#cdcaff
palette = 14=#c4c5ff
palette = 15=#d3d4ff
