mode = "dark"

accent = "#6e94b2"

bg         = "#141415"
dark_bg    = "#0e0e0f"
darker_bg  = "#090909"
lighter_bg = "#252530"
selection  = "#405065"
muted      = "#4e576e"
dark_fg    = "#606079"
fg         = "#cdcdcd"
light_fg   = "#d2d2d2"
bright_fg  = "#d7d7d7"

red     = "#d8647e"
yellow  = "#f3be7c"
orange  = "#e48c7d"
green   = "#7fa563"
cyan    = "#aeaed1"
blue    = "#6e94b2"
magenta = "#bb9dbd"
brown   = "#62343f"

bright_red     = "#e08398"
bright_yellow  = "#f5cb96"
bright_green   = "#99b782"
bright_cyan    = "#bebeda"
bright_blue    = "#8ba9c1"
bright_magenta = "#c9b1ca"
