{
  "schema": 1,
  "colors": {
    "frame": "{{ bg }}",
    "frame_inactive": "{{ mix bg fg 8% }}",
    "tab_background_text": "{{ mix fg bg 25% }}",
    "tab_selected": "{{ mix bg fg 6% }}",
    "tab_text": "{{ fg }}",
    "tab_line": "{{ accent }}",
    "tab_loading": "{{ accent }}",
    "icons": "{{ mix fg bg 15% }}",
    "icons_attention": "{{ accent }}",
    "toolbar": "{{ mix bg fg 6% }}",
    "toolbar_text": "{{ fg }}",
    "toolbar_field": "{{ mix bg fg 10% }}",
    "toolbar_field_text": "{{ fg }}",
    "toolbar_field_border": "{{ mix bg fg 20% }}",
    "toolbar_field_focus": "{{ mix bg accent 12% }}",
    "toolbar_field_text_focus": "{{ fg }}",
    "toolbar_field_border_focus": "{{ accent }}",
    "toolbar_top_separator": "{{ mix bg fg 15% }}",
    "toolbar_bottom_separator": "{{ mix bg fg 15% }}",
    "toolbar_vertical_separator": "{{ mix bg fg 15% }}",
    "button_background_hover": "{{ mix bg fg 10% }}",
    "button_background_active": "{{ mix bg fg 18% }}",
    "popup": "{{ bg }}",
    "popup_text": "{{ fg }}",
    "popup_border": "{{ mix bg fg 20% }}",
    "popup_highlight": "{{ selection }}",
    "popup_highlight_text": "{{ bright_fg }}",
    "sidebar": "{{ bg }}",
    "sidebar_text": "{{ fg }}",
    "sidebar_border": "{{ mix bg fg 15% }}",
    "ntp_background": "{{ bg }}",
    "ntp_text": "{{ fg }}"
  }
}
