# Omarchy mpv bindings

MBTN_LEFT      cycle pause
SPACE          cycle pause
p              cycle pause
q              quit
Q              quit-watch-later
s              stop
r              seek 0 absolute

LEFT           seek -10
RIGHT          seek 10
UP             add volume 5
DOWN           add volume -5

Shift+LEFT     seek -3 exact
Shift+RIGHT    seek 3 exact
Ctrl+LEFT      seek -60
Ctrl+RIGHT     seek 60

f              cycle fullscreen
m              cycle mute
o              cycle-values osd-level 1 3
i              script-binding stats/display-stats-toggle

[              add speed -0.1
]              add speed 0.1
{              add speed -0.25
}              add speed 0.25
BS             set speed 1.0

c              cycle audio
v              cycle sub
b              cycle sub down
j              cycle sub-visibility

S              screenshot
Alt+s          screenshot video

PGUP           playlist-prev
PGDWN          playlist-next
