// Package omarchy renders and installs Omarchy themes from a generated palette.
package omarchy

import (
	"fmt"
	"strings"

	"omarchy-colorgen/internal/palette"
)

// ColorsTOML renders a palette as an Omarchy colors.toml document. The layout
// mirrors the first-party themes: mode, accent, the bg/fg ramp, the color
// group, then the bright_* group. wallpaper is recorded in a header comment.
func ColorsTOML(p palette.Palette, wallpaper string) string {
	var b strings.Builder

	b.WriteString("# Generated by omarchy-colorgen\n")
	if wallpaper != "" {
		fmt.Fprintf(&b, "# Source wallpaper: %s\n", wallpaper)
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "mode = %q\n\n", p.Mode)
	fmt.Fprintf(&b, "accent = %q\n\n", p.Accent)

	writeKV(&b, "bg", p.Bg)
	writeKV(&b, "dark_bg", p.DarkBg)
	writeKV(&b, "darker_bg", p.DarkerBg)
	writeKV(&b, "lighter_bg", p.LighterBg)
	writeKV(&b, "selection", p.Selection)
	writeKV(&b, "muted", p.Muted)
	writeKV(&b, "dark_fg", p.DarkFg)
	writeKV(&b, "fg", p.Fg)
	writeKV(&b, "light_fg", p.LightFg)
	writeKV(&b, "bright_fg", p.BrightFg)
	b.WriteString("\n")

	writeKV(&b, "red", p.Red)
	writeKV(&b, "yellow", p.Yellow)
	writeKV(&b, "orange", p.Orange)
	writeKV(&b, "green", p.Green)
	writeKV(&b, "cyan", p.Cyan)
	writeKV(&b, "blue", p.Blue)
	writeKV(&b, "magenta", p.Magenta)
	writeKV(&b, "brown", p.Brown)
	b.WriteString("\n")

	writeKV(&b, "bright_red", p.BrightRed)
	writeKV(&b, "bright_yellow", p.BrightYellow)
	writeKV(&b, "bright_green", p.BrightGreen)
	writeKV(&b, "bright_cyan", p.BrightCyan)
	writeKV(&b, "bright_blue", p.BrightBlue)
	writeKV(&b, "bright_magenta", p.BrightMagenta)

	return b.String()
}

func writeKV(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%s = %q\n", key, value)
}
