[colors]
[colors.primary]
background = "#080810"
foreground = "#F4F1C4"

[colors.normal]
black   = "#080810"
red     = "#c6826e"
green   = "#f4b474"
yellow  = "#ffdc97"
blue    = "#b26677"
magenta = "#ee8c8a"
cyan    = "#ffcf64"
white   = "#F4F1C4"

[colors.bright]
black   = "#5f5f66"
red     = "#e79279"
green   = "#ffc66f"
yellow  = "#ffd57d"
blue    = "#d2748a"
magenta = "#ff9897"
cyan    = "#ffe356"
white   = "#fff2ee"

[colors.cursor]
text   = "#080810"
cursor = "#F4F1C4"
