# Background and foreground colors
background = #080810
foreground = #F4F1C4

# Standard colors
palette = 0=#080810
palette = 1=#c6826e
palette = 2=#f4b474
palette = 3=#ffdc97
palette = 4=#b26677
palette = 5=#ee8c8a
palette = 6=#ffcf64
palette = 7=#F4F1C4

# Bright colors
palette = 8=#5f5f66
palette = 9=#e79279
palette = 10=#ffc66f
palette = 11=#ffd57d
palette = 12=#d2748a
palette = 13=#ff9897
palette = 14=#ffe356
palette = 15=#fff2ee
