$color = rgba(8, 8, 16, 1)
$inner_color = rgba(8, 8, 16, 0.66)
$outer_color = rgba(238, 140, 138, 1)
$font_color = rgba(244, 241, 196, 1)
$placeholder_color = rgba(244, 241, 196, 0.7)
$check_color = rgba(255, 207, 100, 1)
