background            #080810
foreground            #F4F1C4

# black
color0  #080810
color8  #5f5f66

# red
color1  #c6826e
color9  #e79279

# green
color2  #f4b474
color10 #ffc66f

# yellow
color3  #ffdc97
color11 #ffd57d

# blue
color4  #b26677
color12 #d2748a

# magenta
color5  #ee8c8a
color13 #ff9897

#cyan
color6  #ffcf64
color14 #ffe356

#white
color7  #F4F1C4
color15 #fff2ee


