[colors]
[colors.primary]
background = "#141520"
foreground = "#c9cbe8"

[colors.normal]
black   = "#141520"
red     = "#a5a6d0"
green   = "#b7bae1"
yellow  = "#c0c4ec"
blue    = "#a7aad5"
magenta = "#b0afda"
cyan    = "#babde5"
white   = "#c9cbe8"

[colors.bright]
black   = "#626369"
red     = "#c8c7fc"
green   = "#c1c2ff"
yellow  = "#caccff"
blue    = "#c7c9ff"
magenta = "#cdcaff"
cyan    = "#c4c5ff"
white   = "#d3d4ff"

[colors.cursor]
text   = "#141520"
cursor = "#c9cbe8"
