background            #141520
foreground            #c9cbe8

# black
color0  #141520
color8  #626369

# red
color1  #a5a6d0
color9  #c8c7fc

# green
color2  #b7bae1
color10 #c1c2ff

# yellow
color3  #c0c4ec
color11 #caccff

# blue
color4  #a7aad5
color12 #c7c9ff

# magenta
color5  #b0afda
color13 #cdcaff

#cyan
color6  #babde5
color14 #c4c5ff

#white
color7  #c9cbe8
color15 #d3d4ff


